//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontModifier {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.Label ShowText;
        
        protected System.Web.UI.WebControls.RadioButton RadioButton1;
        
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonList;
        
        protected System.Web.UI.WebControls.ListItem red;
        
        protected System.Web.UI.WebControls.ListItem blue;
        
        protected System.Web.UI.WebControls.ListItem yellow;
        
        protected System.Web.UI.WebControls.CheckBox CheckBox1;
        
        protected System.Web.UI.WebControls.CheckBox CheckBox2;
        
        protected System.Web.UI.WebControls.CheckBox CheckBox3;
    }
}
